### ISSUE TITLE
Plugins Install

### ISSUE THREAD

**Issue by RickHays** [n0nag0n/fatfree-devtools#19]
Tried to install "F-3 Mailer" Plugin and received an error.

![image](https://user-images.githubusercontent.com/81177963/226971909-58a28667-cf4e-4376-abc4-a0bd7f878f98.png)

Please let me know if you need anything else.

Rick

**Comment by n0nag0n** [comment]
Just curious if this happens with other plugins, or just that one specifically?

**Comment by RickHays** [comment]
It happens with all of the ones I tried.  Here is a copy of my vendor dir.

![image](https://user-images.githubusercontent.com/81177963/227570402-2841e870-ea56-43aa-889a-f7b3f9e79870.png)

**Comment by RickHays** [comment]
And I also get this when I select "Manage Composer" off of the Admin Menu.  So something Composer Related?

![image](https://user-images.githubusercontent.com/81177963/227667369-9184a2f2-6b64-4138-922e-b9fbbe12e763.png)

**Comment by n0nag0n** [comment]
Should be fixed now with latest release 0.4.0 https://github.com/n0nag0n/fatfree-devtools/commit/29294ccf55360c8c44df4616806cf5dda438651f

**Comment by RickHays** [comment]
Ran like a charm.  Thank you.
