### ISSUE TITLE
need a common on error handler

### ISSUE THREAD

**Issue by pannet1** [n0nag0n/fatfree-devtools#3]
hi,
would like to add a on error function for example if there is no such route. bcosca already has one, would like to have your thoughts on this.

**Comment by n0nag0n** [comment]
Can you give me an example of what you were doing that would cause the route to not show up? Or are you talking about in your project that you're building, you want some kind of a way to configure `$fw->ONERROR` ? A few more specifics would be helpful.

**Comment by pannet1** [comment]
bcosca in his cms first application had a function to handle error. even now i never really understood how that works :-)
i could just drop it in my project and it may magically work.  
here, i just thought every f3 app would require an ONERROR handler and it is a must have addition to dev tools.  i think you will never find any time to make additions to devtools due to your busy schedule. if we add each feature to it every week/month, soon it will become an amazing tool for everyone to use.
short answer to you. its kind of both, i want one in my current project and also add it to devtools for everyone to use in future.
note: if someone accidentally types a route, i guess f3 will show some error.

`Not Found`

`HTTP 404 (GET /ad)`
`[vendor/bcosca/fatfree-core/base.php:1792] Base->error()`
`[index.php:6] Base->run()`

**Comment by n0nag0n** [comment]
You don't have to configure ONERROR for your app to work, only if you want it to handle something special for you. I'll mark this as a potential feature in the project for devtools.
