### ISSUE TITLE
Serve admin had error on "Manage Composer" menu

### ISSUE THREAD

**Issue by soulhd** [n0nag0n/fatfree-devtools#6]
I'm using Fat-Free Dev Tools v-0.1.2 and bcosca/fatfree-core v3.8, with composer that I installed with scoop package manager on Windows 11

Whenever I access **Manage Composer** (http://localhost:8081/manage-composer?composer=self_update) I got these on the Command Return Value panel:
```
Class 'Nettools\ComposerInterface\Config' not found
---
Trace : #0 C:\Users\mrashdan\scoop\persist\composer\home\vendor\bcosca\fatfree-core\base.php(1984): n0nag0n\Manage_Composer_Controller->indexAction(Object(Base), Array, 'n0nag0n\\Manage_...')
#1 C:\Users\mrashdan\scoop\persist\composer\home\vendor\bcosca\fatfree-core\base.php(1783): Base->call(Array, Array, Array)
#2 C:\Users\mrashdan\scoop\persist\composer\home\vendor\n0nag0n\fatfree-devtools\public\index.php(17): Base->run()
#3 {main}
```
What does it mean and how to fix it if it was an error?

**Comment by n0nag0n** [comment]
Sorry wasn't notified of your issue. Did you install this locally or did you install this as part of a project you're working on. I just wonder if you ran `composer install` if you did it locally or not. The other thing I wonder is if the version was updated and broke part of it?

**Comment by n0nag0n** [comment]
No response. Closing.
