### ISSUE TITLE
Devtools not working with PHP 8.0

### ISSUE THREAD

**Issue by mp-itconsulting** [n0nag0n/fatfree-devtools#8]
After installing the latest version and try to strat "fatfree serve admin" the start screens shows up. But after clicking "next" an 500 error is produced (PHP 8.0.25, F3 3.8.1):

[Wed Nov  9 16:45:15 2022] [::1]:45402 Accepted
[Wed Nov  9 16:45:15 2022] Undefined array key "title"
[Wed Nov  9 16:45:15 2022] [/srv/www/applications/fatfree-tutorials/vendor/n0nag0n/fatfree-devtools/tmp/1rhmuqyegwrps.oxaffohovz0u.php:8] 
[Wed Nov  9 16:45:15 2022] [/srv/www/applications/fatfree-tutorials/vendor/n0nag0n/fatfree-devtools/tmp/1rhmuqyegwrps.oxaffohovz0u.php:8] Base->{closure}()
[Wed Nov  9 16:45:15 2022] [/srv/www/applications/fatfree-tutorials/vendor/bcosca/fatfree-core/base.php:2953] require('/srv/www/applications/fatfree-tutorials/vendor/n0nag0n/fatfree-devtools/tmp/1rhmuqyegwrps.oxaffohovz0u.php')
[Wed Nov  9 16:45:15 2022] [/srv/www/applications/fatfree-tutorials/vendor/bcosca/fatfree-core/base.php:3197] View->sandbox()
[Wed Nov  9 16:45:15 2022] [/srv/www/applications/fatfree-tutorials/vendor/n0nag0n/fatfree-devtools/tmp/1rhmuqyegwrps.2kzhuyuouyyos.php:70] Preview->render()
[Wed Nov  9 16:45:15 2022] [/srv/www/applications/fatfree-tutorials/vendor/bcosca/fatfree-core/base.php:2953] require('/srv/www/applications/fatfree-tutorials/vendor/n0nag0n/fatfree-devtools/tmp/1rhmuqyegwrps.2kzhuyuouyyos.php')
[Wed Nov  9 16:45:15 2022] [/srv/www/applications/fatfree-tutorials/vendor/bcosca/fatfree-core/base.php:3197] View->sandbox()
[Wed Nov  9 16:45:15 2022] [/srv/www/applications/fatfree-tutorials/vendor/n0nag0n/fatfree-devtools/controllers/Base_Controller.php:28] Preview->render()
[Wed Nov  9 16:45:15 2022] [/srv/www/applications/fatfree-tutorials/vendor/n0nag0n/fatfree-devtools/controllers/Init_Environment_Controller.php:57] n0nag0n\Base_Controller->renderHtml()
[Wed Nov  9 16:45:15 2022] [/srv/www/applications/fatfree-tutorials/vendor/bcosca/fatfree-core/base.php:1995] n0nag0n\Init_Environment_Controller->pageAction()
[Wed Nov  9 16:45:15 2022] [/srv/www/applications/fatfree-tutorials/vendor/bcosca/fatfree-core/base.php:1794] Base->call()

![image](https://user-images.githubusercontent.com/1751933/200876286-648c5d01-c21c-41f6-b833-006f5f4b8976.png)

Kr
Michael

**Comment by n0nag0n** [comment]
Well that's fun :) All my dev environments I work on are 7.4 so this was likely missed. The probably is that there's probably a missing !empty() somewhere that throws that error. It'd be an easy PR since you already have the environment up and running to see what fields need either `!empty()`, `isset()`, or something like `$var ?? ''`

**Comment by n0nag0n** [comment]
Actually I think I can mess with it in php7.4 lemme see if it's easy.

**Comment by n0nag0n** [comment]
I think I got all the changes. Make sure you update with `composer update n0nag0n/fatfree-devtools`.
